### ISSUE TITLE
Ikonky pre kategórie

### ISSUE THREAD

**Issue by bukajis** [SimonFenak/DiaBee#4]
Pridaj ikonky k kategóriám. 
Obrázok a pod ním názov kategórie ako text

**Comment by durkii** [comment]
[Ikony.zip](https://github.com/user-attachments/files/15752618/Ikony.zip)

**Comment by durkii** [comment]
[Ikony+Pozadie.zip](https://github.com/user-attachments/files/15752627/Ikony%2BPozadie.zip)
